/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppDocumentationRouteImport } from './routes/_app.documentation'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app.settings.general'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app.settings.api-keys'
import { Route as AppProjectsRecentRouteImport } from './routes/_app.projects.recent'
import { Route as AppProjectsAllRouteImport } from './routes/_app.projects.all'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppDocumentationIntroductionRouteImport } from './routes/_app.documentation.introduction'
import { Route as AppDocumentationGetStartedRouteImport } from './routes/_app.documentation.get-started'
import { Route as AppDocumentationChangelogRouteImport } from './routes/_app.documentation.changelog'
import { ServerRoute as ApiSessionServerRouteImport } from './routes/api/session'
import { ServerRoute as ApiSandboxStreamServerRouteImport } from './routes/api/sandbox/stream'

const rootServerRouteImport = createServerRootRoute()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsRecentRoute = AppProjectsRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsAllRoute = AppProjectsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppDocumentationIntroductionRoute =
  AppDocumentationIntroductionRouteImport.update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => AppDocumentationRoute,
  } as any)
const AppDocumentationGetStartedRoute =
  AppDocumentationGetStartedRouteImport.update({
    id: '/get-started',
    path: '/get-started',
    getParentRoute: () => AppDocumentationRoute,
  } as any)
const AppDocumentationChangelogRoute =
  AppDocumentationChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AppDocumentationRoute,
  } as any)
const ApiSessionServerRoute = ApiSessionServerRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSandboxStreamServerRoute = ApiSandboxStreamServerRouteImport.update({
  id: '/api/sandbox/stream',
  path: '/api/sandbox/stream',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/documentation': typeof AppDocumentationRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/': typeof AppIndexRoute
  '/documentation/changelog': typeof AppDocumentationChangelogRoute
  '/documentation/get-started': typeof AppDocumentationGetStartedRoute
  '/documentation/introduction': typeof AppDocumentationIntroductionRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/all': typeof AppProjectsAllRoute
  '/projects/recent': typeof AppProjectsRecentRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/general': typeof AppSettingsGeneralRoute
}
export interface FileRoutesByTo {
  '/documentation': typeof AppDocumentationRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/': typeof AppIndexRoute
  '/documentation/changelog': typeof AppDocumentationChangelogRoute
  '/documentation/get-started': typeof AppDocumentationGetStartedRoute
  '/documentation/introduction': typeof AppDocumentationIntroductionRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/all': typeof AppProjectsAllRoute
  '/projects/recent': typeof AppProjectsRecentRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/general': typeof AppSettingsGeneralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/documentation': typeof AppDocumentationRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/documentation/changelog': typeof AppDocumentationChangelogRoute
  '/_app/documentation/get-started': typeof AppDocumentationGetStartedRoute
  '/_app/documentation/introduction': typeof AppDocumentationIntroductionRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/all': typeof AppProjectsAllRoute
  '/_app/projects/recent': typeof AppProjectsRecentRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/documentation'
    | '/projects'
    | '/settings'
    | '/'
    | '/documentation/changelog'
    | '/documentation/get-started'
    | '/documentation/introduction'
    | '/projects/$projectId'
    | '/projects/all'
    | '/projects/recent'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/general'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/documentation'
    | '/projects'
    | '/settings'
    | '/'
    | '/documentation/changelog'
    | '/documentation/get-started'
    | '/documentation/introduction'
    | '/projects/$projectId'
    | '/projects/all'
    | '/projects/recent'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/general'
  id:
    | '__root__'
    | '/_app'
    | '/_app/documentation'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/'
    | '/_app/documentation/changelog'
    | '/_app/documentation/get-started'
    | '/_app/documentation/introduction'
    | '/_app/projects/$projectId'
    | '/_app/projects/all'
    | '/_app/projects/recent'
    | '/_app/settings/api-keys'
    | '/_app/settings/billing'
    | '/_app/settings/general'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/session': typeof ApiSessionServerRoute
  '/api/sandbox/stream': typeof ApiSandboxStreamServerRoute
}
export interface FileServerRoutesByTo {
  '/api/session': typeof ApiSessionServerRoute
  '/api/sandbox/stream': typeof ApiSandboxStreamServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/session': typeof ApiSessionServerRoute
  '/api/sandbox/stream': typeof ApiSandboxStreamServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/session' | '/api/sandbox/stream'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/session' | '/api/sandbox/stream'
  id: '__root__' | '/api/session' | '/api/sandbox/stream'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSessionServerRoute: typeof ApiSessionServerRoute
  ApiSandboxStreamServerRoute: typeof ApiSandboxStreamServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/recent': {
      id: '/_app/projects/recent'
      path: '/recent'
      fullPath: '/projects/recent'
      preLoaderRoute: typeof AppProjectsRecentRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/all': {
      id: '/_app/projects/all'
      path: '/all'
      fullPath: '/projects/all'
      preLoaderRoute: typeof AppProjectsAllRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/documentation/introduction': {
      id: '/_app/documentation/introduction'
      path: '/introduction'
      fullPath: '/documentation/introduction'
      preLoaderRoute: typeof AppDocumentationIntroductionRouteImport
      parentRoute: typeof AppDocumentationRoute
    }
    '/_app/documentation/get-started': {
      id: '/_app/documentation/get-started'
      path: '/get-started'
      fullPath: '/documentation/get-started'
      preLoaderRoute: typeof AppDocumentationGetStartedRouteImport
      parentRoute: typeof AppDocumentationRoute
    }
    '/_app/documentation/changelog': {
      id: '/_app/documentation/changelog'
      path: '/changelog'
      fullPath: '/documentation/changelog'
      preLoaderRoute: typeof AppDocumentationChangelogRouteImport
      parentRoute: typeof AppDocumentationRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/sandbox/stream': {
      id: '/api/sandbox/stream'
      path: '/api/sandbox/stream'
      fullPath: '/api/sandbox/stream'
      preLoaderRoute: typeof ApiSandboxStreamServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppDocumentationRouteChildren {
  AppDocumentationChangelogRoute: typeof AppDocumentationChangelogRoute
  AppDocumentationGetStartedRoute: typeof AppDocumentationGetStartedRoute
  AppDocumentationIntroductionRoute: typeof AppDocumentationIntroductionRoute
}

const AppDocumentationRouteChildren: AppDocumentationRouteChildren = {
  AppDocumentationChangelogRoute: AppDocumentationChangelogRoute,
  AppDocumentationGetStartedRoute: AppDocumentationGetStartedRoute,
  AppDocumentationIntroductionRoute: AppDocumentationIntroductionRoute,
}

const AppDocumentationRouteWithChildren =
  AppDocumentationRoute._addFileChildren(AppDocumentationRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsAllRoute: typeof AppProjectsAllRoute
  AppProjectsRecentRoute: typeof AppProjectsRecentRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsAllRoute: AppProjectsAllRoute,
  AppProjectsRecentRoute: AppProjectsRecentRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppDocumentationRoute: typeof AppDocumentationRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentationRoute: AppDocumentationRouteWithChildren,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSessionServerRoute: ApiSessionServerRoute,
  ApiSandboxStreamServerRoute: ApiSandboxStreamServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
